### ISSUE TITLE
Error while running <xcrun --sdk iphoneos --find llvm-gcc>

### ISSUE THREAD

**Issue by chengzhf** [Parrot-Developers/Docs#1]
I follow the install instructions and run the command line "SDK3Build.py -t iOS", but it throws the error: 'Error while running <xcrun --sdk iphoneos --find llvm-gcc>'. It seems that the llvm-gcc couldn't be recogniezd. Can you help me to fix this problem? Thanks. My enviroment: mac os 10.9.5, XCode 6.1, iOS SDK 8.1.

**Comment by N-Bz** [comment]
Hi,

Can you provide a full output of the `./SDK3Build.py -t iOS` command ?

The fact that we can't locate llvm-gcc should not abort the build (as we will use gcc instead), even if reported as an "error", so the real error may lie in further lines in the log (or in a bug in the build script when llvm-gcc is not found).

As a reference, I use the following setup : OSX Yosemite 10.10.1, XCode 6.1, iOS SDK 8.1.
Did you install the Command Line tools for XCode ? (in a terminal, try `xcode-select --install`)

Regards,
Nicolas.

**Comment by chengzhf** [comment]
Thank you very much for answering so quickly. I have try "xcode-select --install" in a terminal and the command line tools are ok. The full output of the ./SDK3Build.py -t iOS command is attached here, can you help me to find out what had happened?

[Log removed for lisibility]

**Comment by chengzhf** [comment]
I install libtool and build again. But there are still errors

**Comment by N-Bz** [comment]
What does output the `CheckEnv.py` script ? You may still be missing something.

If you want to be sure, you can make a full clean with the `./SDK3Build.py --all-cleanup` command, and then try again. It will remove any "bad" build product that may have been generated by the previous builds.
