### ISSUE TITLE
Missing libARDiscovery Documentation

### ISSUE THREAD

**Issue by weaversa** [Parrot-Developers/Docs#2]
All the rest of the documentation seem to be in this repo, but `libARDiscovery` isn't in either of the `Unix` or `iOS` directories. If it's easy to add it, I would appreciate it. Thanks!

**Comment by weaversa** [comment]
Maybe found the problem ---
The doxygen file for `libARDiscovery`
https://github.com/ARDroneSDK3/libARDiscovery/blob/master/Build/doxygen.cfg
has
`PROJECT_NAME           = libARNetworkAL`

**Comment by N-Bz** [comment]
Owww ... 
Thanks a lot !

I'll fix this monday and commit the good generated doc asap ;)

**Comment by weaversa** [comment]
Thank you!
